/**
 * Estilos globales de la tienda (generados según escala de pantalla).
 * Un solo StyleSheet evita recrear objetos en cada render de hijos.
 */
import { StyleSheet } from 'react-native';

/**
 * Crea el StyleSheet global de la tienda.
 * @param scale Factor 0.78–1.14 según ancho (referencia 390px)
 * @param isTablet true si ancho ≥ 768 (más columnas en el grid)
 * @param screenWidth Ancho útil para calcular columnas del catálogo
 */
export function createAppStyles(
  scale: number,
  _isSmallScreen: boolean,
  isTablet: boolean,
  screenWidth: number
) {
  // scale: factor 0.78–1.14 según ancho; isTablet ajusta columnas del grid
  return StyleSheet.create({
  // ─── Admin (AdminModal / AdminPanel) ─────────────────────────────────
  actionsRow: {flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  addBtn: {backgroundColor: '#d2b06b', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16 }, // AdminPanel "+ Nuevo"
  addButton: {backgroundColor: '#b4812f', // legacy / alias
  },
  adminLink: { color: '#d2b06b', marginTop: Math.round(8 * scale), fontSize: Math.round(13 * scale), fontWeight: '700' }, // ContactSection → admin
  adminModalClose: {color: '#d2b06b', fontSize: Math.round(15 * scale), fontWeight: '700'},
  adminModalHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(12 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  adminModalSheet: { flex: 1, backgroundColor: '#0a0908' },
  adminModalRoot: { flex: 1, backgroundColor: '#0a0908' },
  adminModalTitle: {color: '#f4ead8', fontSize: Math.round(17 * scale), fontWeight: '800'},
  brandName: { color: '#f5ebdd', fontSize: Math.round(15 * scale), fontWeight: '700' },
  btnText: { color: '#fff', fontWeight: '700', fontSize: Math.round(12 * scale) },
  buttonText: {color: '#fff',
    fontWeight: '700',
  },
  cartBadge: {position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#2bd56f',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  cartBadgeText: {fontSize: 10, fontWeight: '800', color: '#052010' },
  cartBar: {position: 'absolute',
    left: 8,
    right: 8,
    bottom: 8,
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    padding: 10,
  },
  cartBarButton: {backgroundColor: '#1d8f43', borderRadius: 10, alignItems: 'center', paddingVertical: 10 },
  cartBarButtonText: {color: '#f3fff7', fontWeight: '700' },
  cartBarText: {color: '#f0e1c8', fontSize: 15, marginBottom: 8 },
  cartBox: {backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: '#eadfce',
    padding: 12,
    marginHorizontal: 8,
    marginBottom: 8,
    marginTop: 4,
  },
  // ─── Carrito (TopNav badge, CartModal, barra inferior legacy) ───────
  cartIcon: {width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#534126',
    backgroundColor: '#1b1813',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartIconText: { color: '#f4d8a3', fontSize: Math.round(16 * scale) },
  // ─── Modal carrito (CartModal.tsx) ─────────────────────────────────
  cartModalBack: {color: '#d2b06b', fontSize: Math.round(14 * scale), fontWeight: '700'},
  cartModalBackBtn: {paddingVertical: Math.round(6 * scale)},
  cartModalBody: {paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(12 * scale)},
  cartModalEmpty: {color: '#8a7d6a', textAlign: 'center', paddingVertical: Math.round(32 * scale), fontSize: Math.round(15 * scale)},
  cartModalFooter: {padding: Math.round(16 * scale), borderTopWidth: 1, borderTopColor: '#2a2217'},
  cartModalHeader: {flexDirection: 'row', alignItems: 'center', paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(14 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  cartModalLine: {flexDirection: 'row', alignItems: 'center', gap: Math.round(10 * scale), marginBottom: Math.round(12 * scale)},
  cartModalLineInfo: {flex: 1},
  cartModalLineName: {color: '#f4ead8', fontSize: Math.round(14 * scale), fontWeight: '700'},
  cartModalLinePrice: {color: '#d9b778', fontSize: Math.round(13 * scale), marginTop: Math.round(4 * scale)},
  cartModalQtyBtn: {width: Math.round(32 * scale), height: Math.round(32 * scale), borderRadius: Math.round(8 * scale), backgroundColor: '#2a2418', alignItems: 'center', justifyContent: 'center'},
  cartModalQtyRow: {flexDirection: 'row', alignItems: 'center', gap: Math.round(8 * scale)},
  cartModalQtyText: {color: '#f4ead8', fontSize: Math.round(15 * scale), fontWeight: '800', minWidth: Math.round(24 * scale), textAlign: 'center'},
  cartModalSendBtn: {backgroundColor: '#1d8f43', borderRadius: Math.round(12 * scale), paddingVertical: Math.round(14 * scale), alignItems: 'center'},
  cartModalSendText: {color: '#fff', fontWeight: '800', fontSize: Math.round(15 * scale)},
  cartModalTitle: {flex: 1, textAlign: 'center', color: '#f4ead8', fontSize: Math.round(18 * scale), fontWeight: '800'},
  cartModalTotal: {color: '#f4ead8', fontSize: Math.round(17 * scale), fontWeight: '800', marginBottom: Math.round(12 * scale)},
  cartTitle: {color: '#3d2d1d',
    fontWeight: '700',
  },
  cartTopRow: {flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cartTotal: {color: '#1d8f43',
    fontWeight: '700',
  },
  categoriesContainer: {gap: 8,
    paddingVertical: 8,
    paddingRight: 16,
  },
  categoriesWrap: {flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  // ─── Categorías (CategoryGrid, chips legacy) ─────────────────────────
  // Tarjeta de categoría ~31% → ~3 por fila (CategoryGrid)
  categoryCard: {
    backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: Math.round(10 * scale),
    paddingVertical: Math.round(8 * scale),
    paddingHorizontal: Math.round(4 * scale),
    width: '31%',
    flexGrow: 0,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: Math.round(58 * scale),
  },
  categoryCardActive: { borderColor: '#d2b06b', backgroundColor: '#242016' },
  categoryCardIcon: { fontSize: Math.round(20 * scale), marginBottom: Math.round(4 * scale) },
  categoryCardText: {
    color: '#f0e3cc',
    fontSize: Math.round(10 * scale),
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: Math.round(13 * scale),
  },
  categoryChip: {backgroundColor: '#fff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfd2bf',
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  categoryChipActive: {backgroundColor: '#f1d39d',
    borderColor: '#b07a24',
  },
  categoryEmoji: {fontSize: 14,
  },
  categoryEmojiActive: {transform: [{ scale: 1.05 }],
  },
  // Filtro de categorías: ~3 tarjetas por fila con flexWrap
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: Math.round(5 * scale),
    rowGap: Math.round(6 * scale),
    justifyContent: 'space-between',
  },
  categoryText: {color: '#4f3f2e',
    fontWeight: '600',
    fontSize: 13,
  },
  categoryTextActive: {color: '#3d2a12',
  },
  // ─── Contacto y CTA (ContactSection, botones WhatsApp en home) ───────
  contactButton: {backgroundColor: '#2ddb74',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 18,
  },
  contactButtonText: { color: '#eaffef', fontWeight: '800', fontSize: Math.round(15 * scale) },
  contactLead: { color: '#ded2bf', fontSize: Math.round(15 * scale), fontWeight: '700', textAlign: 'center' },
  contactText: { color: '#baa98f', fontSize: Math.round(14 * scale), textAlign: 'center', marginTop: Math.round(8 * scale), lineHeight: Math.round(21 * scale) },
  container: {flex: 1, backgroundColor: '#0f0e0c' }, // legacy; raíz real es safeArea + appRoot
  // ─── Detalle de producto (ProductDetailModal, galería) ───────────────
  detailModalAddBtn: {backgroundColor: '#d2b06b', borderRadius: Math.round(12 * scale), paddingVertical: Math.round(14 * scale), alignItems: 'center', marginTop: Math.round(16 * scale)},
  detailModalBody: {padding: Math.round(16 * scale)},
  detailModalCloseBtn: {position: 'absolute', top: Math.round(12 * scale), right: Math.round(12 * scale), backgroundColor: 'rgba(0,0,0,0.55)', borderRadius: Math.round(20 * scale), width: Math.round(36 * scale), height: Math.round(36 * scale), alignItems: 'center', justifyContent: 'center'},
  detailModalCloseText: {color: '#fff', fontSize: Math.round(18 * scale), fontWeight: '700'},
  detailModalDesc: {color: '#9c8f7b', fontSize: Math.round(14 * scale), lineHeight: Math.round(20 * scale), marginTop: Math.round(12 * scale)},
  detailModalImage: { width: '100%', height: Math.round(280 * scale), backgroundColor: '#1a1814' },
  detailImagesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: Math.round(8 * scale),
    columnGap: Math.round(8 * scale),
    paddingHorizontal: Math.round(12 * scale),
    paddingTop: Math.round(12 * scale),
  },
  detailImageCell: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: Math.round(10 * scale),
    overflow: 'hidden',
    backgroundColor: '#1a1814',
  },
  detailImageCellFull: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: Math.round(10 * scale),
    overflow: 'hidden',
    backgroundColor: '#1a1814',
  },
  detailModalImageThumb: { width: '100%', height: '100%' },
  detailModalPrice: {color: '#d9b778', fontSize: Math.round(18 * scale), fontWeight: '800', marginTop: Math.round(8 * scale)},
  detailModalSheet: {backgroundColor: '#12100c', marginHorizontal: Math.round(12 * scale), borderRadius: Math.round(18 * scale), overflow: 'hidden', maxHeight: '88%'},
  detailModalTitle: {color: '#f4ead8', fontSize: Math.round(20 * scale), fontWeight: '800'},
  emptyText: {textAlign: 'center', color: '#7a6651', paddingVertical: 24, fontSize: 14 }, // catálogo vacío
  // Chips de filtro horizontales (legacy; categorías usan categoryCard)
  filterChip: {borderWidth: 1,
    borderColor: '#3b3227',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  filterChipActive: {backgroundColor: '#d2b06b', borderColor: '#d2b06b' },
  filterChipText: { color: '#bfae91', fontWeight: '600', fontSize: Math.round(12 * scale) },
  filterChipTextActive: {color: '#20190f' },
  filterWrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  // Pie de ContactSection (marca, copyright, enlace admin)
  footerBox: {marginTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#2a2217',
    paddingTop: 16,
    alignItems: 'center',
    paddingBottom: 16,
  },
  footerBrand: { color: '#f0e2cc', fontSize: Math.round(15 * scale), fontWeight: '600' },
  footerText: { color: '#9c8f7b', marginTop: Math.round(6 * scale), textAlign: 'center', fontSize: Math.round(12 * scale) },
  headerContainer: {paddingHorizontal: 16, paddingTop: 8, paddingBottom: 8 }, // legacy header
  headerTop: {backgroundColor: '#18130f', // tarjeta resumen legacy
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#3a2d1f',
    padding: 14,
    marginBottom: 10,
  },
  // ─── Inicio / Hero (HeroSection) ───────────────────────────────────
  heroButton: {alignSelf: 'flex-start',
    marginTop: 22,
    backgroundColor: '#d2b06b',
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: 14,
  },
  heroButtonText: { color: '#1f1a12', fontWeight: '800', fontSize: Math.round(14 * scale) },
  // Bloque inicial (HeroSection)
  heroSection: {
    paddingHorizontal: Math.round(16 * scale),
    paddingTop: Math.round(22 * scale),
    paddingBottom: Math.round(24 * scale),
    backgroundColor: '#090909',
    borderBottomWidth: 1,
    borderBottomColor: '#2a2217',
  },
  heroSubtitle: { color: '#b8ab97', marginTop: Math.round(10 * scale), fontSize: Math.round(14 * scale), lineHeight: Math.round(21 * scale) },
  heroTitle: { color: '#f6efe3', fontSize: Math.round(22 * scale), lineHeight: Math.round(28 * scale), fontWeight: '600' },
  logoText: { color: '#f4e9d9', fontSize: Math.round(17 * scale), fontWeight: '600' }, // TopNav marca
  menuAdminText: { color: '#d2b06b' }, // ítem admin en menú legacy
  menuButton: { width: 44, // hamburguesa TopNav (☰)
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#534126',
    backgroundColor: '#1b1813',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuButtonText: {color: '#f4e9d9', fontSize: Math.round(22 * scale), marginTop: -2 },
  menuItem: {paddingVertical: 10, paddingHorizontal: 12 },
  menuItemText: { color: '#ddd1bb', fontWeight: '600', fontSize: Math.round(14 * scale) },
  // ─── Menú lateral (NavMenu) y overlays de modales ────────────────────
  menuOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', alignItems: 'flex-end', paddingTop: 66, paddingRight: 14 },
  menuPanel: {width: 210,
    backgroundColor: '#171514',
    borderWidth: 1,
    borderColor: '#3d3427',
    borderRadius: 12,
    paddingVertical: 4,
  },
  menuTrigger: {width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#251c12',
    borderWidth: 1,
    borderColor: '#7a5a2b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTriggerText: { color: '#f4d9a8', fontSize: Math.round(16 * scale), marginTop: -1 },
  // Fondo semitransparente de CartModal y ProductDetailModal
  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end'},
  modalSheet: {backgroundColor: '#12100c', borderTopLeftRadius: Math.round(20 * scale), borderTopRightRadius: Math.round(20 * scale), maxHeight: '92%'},
  navMenuCloseArea: {flex: 1},
  navMenuItem: {paddingVertical: Math.round(16 * scale), paddingHorizontal: Math.round(20 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  navMenuItemText: { color: '#f4ead8', fontSize: Math.round(14 * scale), fontWeight: '700' },
  navMenuOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)'},
  navMenuTitle: {color: '#d2b06b', fontSize: Math.round(13 * scale), fontWeight: '800', paddingHorizontal: Math.round(20 * scale), paddingBottom: Math.round(8 * scale), textTransform: 'uppercase'},
  // ─── Catálogo / tarjetas de producto (ProductCatalogSection) ───────
  productActions: {
    flexDirection: 'row',
    gap: Math.round(6 * scale),
    marginTop: Math.round(8 * scale),
  },
  // Tarjeta ~48% del ancho → grid de 2 columnas con flexWrap
  productCard: {
    backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: Math.round(12 * scale),
    overflow: 'hidden',
    width: '48%',
    flexGrow: 0,
  },
  productCardBody: {
    paddingHorizontal: Math.round(8 * scale),
    paddingTop: Math.round(8 * scale),
    paddingBottom: Math.round(10 * scale),
  },
  productContent: {flex: 1,
  },
  productDesc: { color: '#baab94', fontSize: Math.round(12 * scale), paddingHorizontal: Math.round(8 * scale), marginTop: Math.round(4 * scale), lineHeight: Math.round(17 * scale) },
  productDescription: {color: '#6d5a47',
    marginTop: 4,
    fontSize: 13,
  },
  productEmoji: {fontSize: 24,
  },
  productEmojiBox: {width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fef4e5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#efd7b2',
  },
  productImageEmoji: { fontSize: Math.round(32 * scale) },
  // Contenedor cuadrado de la foto en la tarjeta del catálogo
  productImageMock: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#231f17',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#2f2a22',
  },
  productName: {
    color: '#f4ead8',
    fontSize: Math.round(13 * scale),
    fontWeight: '600',
    lineHeight: Math.round(17 * scale),
    minHeight: Math.round(34 * scale),
  },
  productPrice: {
    color: '#d9b778',
    fontSize: Math.round(16 * scale),
    fontWeight: '800',
    marginTop: Math.round(6 * scale),
  },
  productsContainer: {paddingBottom: 14,
    gap: 10,
  },
  // Botón "Quitar" en tarjeta (resta 1 unidad en useCart)
  removeBtn: {backgroundColor: '#85535f', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16 },
  removeButton: {backgroundColor: '#946066',
  },
  // ─── Layout raíz (App.tsx ScrollView, secciones, pasos) ──────────────
  // Contenedor SafeAreaView en App.tsx
  safeArea: {flex: 1, backgroundColor: '#060606' },
  scroll: {flex: 1 },
  // Padding inferior base; App suma insets.bottom + espacio del FAB
  scrollContent: {paddingBottom: Math.round(132 * scale) },
  // Bloque genérico de cada sección (hero, categorías, catálogo, etc.)
  section: { paddingHorizontal: Math.round(16 * scale), paddingTop: Math.round(20 * scale) },
  sectionTitle: { color: '#f4ead8', fontSize: Math.round(18 * scale), fontWeight: '600', marginBottom: Math.round(10 * scale) },
  // Tarjeta de cada paso en HowToBuySection
  stepCard: {backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 14,
    marginBottom: 12,
    alignItems: 'center',
  },
  stepNumber: {
    width: Math.round(36 * scale),
    height: Math.round(36 * scale),
    borderRadius: Math.round(18 * scale),
    backgroundColor: '#d2b06b',
    color: '#1d170f',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: Math.round(18 * scale),
    fontWeight: '800',
    marginBottom: Math.round(8 * scale),
  },
  stepText: { color: '#baa98f', textAlign: 'center', fontSize: Math.round(13 * scale), lineHeight: Math.round(19 * scale) },
  stepTitle: { color: '#f4ead8', fontSize: Math.round(16 * scale), fontWeight: '600', marginBottom: Math.round(4 * scale) },
  subtitle: {color: '#d9c6a2',
    marginTop: 4,
    fontSize: 14,
  },
  summaryChip: {flex: 1,
    backgroundColor: '#18130f',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a2d1f',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  summaryChipLabel: {color: '#bfa98a',
    fontSize: 12,
  },
  summaryChipValue: {color: '#f4e4ca',
    fontWeight: '700',
    marginTop: 2,
  },
  // Chips de resumen (legacy / admin compartir — poco usados en UI actual)
  summaryRow: {flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  title: { color: '#f7ead6', fontSize: Math.round(20 * scale), fontWeight: '800' },
  topBar: {paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // ─── Barra superior (TopNav) y FAB WhatsApp ─────────────────────────
  // Barra superior fija (TopNav.tsx)
  topNav: {height: 68,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2217',
    backgroundColor: '#0f0f0f',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topNavActions: {flexDirection: 'row', alignItems: 'center', gap: 10 },
  whatsFab: {position: 'absolute',
    right: 18,
    bottom: 48,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ddb74',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2ddb74',
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 10,
  },
  whatsFabText: { fontSize: Math.round(22 * scale) },
  whatsappButton: {backgroundColor: '#1a7f3a',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  whatsappButtonText: {color: '#fff',
    fontWeight: '700',
  },
  /* Estilo legacy (no usado); el FAB activo es whatsFab + icono en WhatsAppFab.tsx */
  whatsappFab: {position: 'absolute',
    right: 18,
    bottom: 88,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ddb74',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2ddb74',
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 10,
  },
  // Grid 2 columnas del catálogo (ProductCatalogSection)
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: Math.round(8 * scale),
    rowGap: Math.round(10 * scale),
    justifyContent: 'space-between',
  },
  productImage: { width: '100%', height: '100%' }, // expo-image dentro de tarjeta
  productImageFallback: { justifyContent: 'center', alignItems: 'center' }, // contenedor si falla URI
  // Botón "Cargar más" (useCatalog.loadMoreProducts)
  loadMoreBtn: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#3b3227',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadMoreText: { color: '#d2b06b', fontWeight: '700', fontSize: Math.round(13 * scale) },
  stepsGrid: { gap: 12 }, // HowToBuySection — tres stepCard
  });
}
